### ISSUE TITLE
линтер ругается на енамы

### ISSUE THREAD

**Issue by akiko23** [siriusdevs/homeworks_23#39]
![image](https://github.com/siriusdevs/homeworks_23/assets/101889433/8ac2c988-829a-421b-805d-494015b4aca0)
![image](https://github.com/siriusdevs/homeworks_23/assets/101889433/e65dd06a-0f9d-486e-b278-e3754f407aa3)

flake8 ругается на класс-enum, можно добавить WPS115 в ignore?)

**Comment by siriusdevs** [comment]
wemake-python-styleguide [предлагают использовать snake_case](https://github.com/wemake-services/wemake-python-styleguide/issues/750) для enums

**Comment by akiko23** [comment]
> wemake-python-styleguide [предлагают использовать snake_case](https://github.com/wemake-services/wemake-python-styleguide/issues/750) для enums

понял, переделаю. Я ориентировался на [python.org](https://docs.python.org/3/library/enum.html)
