### ISSUE TITLE
w503 противоречит w504

### ISSUE THREAD

**Issue by n0tsSzzz** [siriusdevs/homeworks_23#4]

**Comment by n0tsSzzz** [comment]
https://www.flake8rules.com/rules/W503.html
https://www.flake8rules.com/rules/W504.html

**Comment by siriusdevs** [comment]
проверил на нашем сетапе модулей для flake8, ошибка не возникает в обоих случаях.

какая-то устаревшая информация у вас, в [актуальных ошибках](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/violations/index.html) даже кодов таких нет.

**Comment by n0tsSzzz** [comment]
<img width="1237" alt="image" src="https://github.com/siriusdevs/homeworks_23/assets/113695390/5cb5dfea-6428-4cb2-916a-91de4078b615">

на сайте есть w503, w504. Если я правильно понял, то при изменении конфига, они начинают учитываться.

**Comment by siriusdevs** [comment]
fix:
секция "ignore" в setup.cfg должна быть названа "extend-ignore", тогда стандартный flake8 ignore не слетает.

в main исправлю, в остальных ветках давайте сами по желанию.
