### ISSUE TITLE
Homework №2 - Question

### ISSUE THREAD

**Issue by tofickbrodaga** [siriusdevs/homeworks_23#40]
Я же правильно понимаю, что функция состоит из нескольких функций, чтобы избежать подобных линтеров? 
Иначе, это превращается в этот ужас, который даже не то, что смотреть, а открывать страшно. 
И вопрос насчет тестов: 
Тесты должны содержать входные файлы в виде .json файлов, раз функция принимает и возвращает файл? 
Просто много что подробно не описано 
![image](https://github.com/siriusdevs/homeworks_23/assets/101170461/df607418-80af-41c3-9921-b48431af1ede)

**Comment by tofickbrodaga** [comment]
- Ошибки, которые содержат проверку try-except актуальны в этом вопросе, а все остальное - не упорядоченный код, на это не стоит обращать внимание.

**Comment by siriusdevs** [comment]
1. да, должна быть основная функция, но она может использовать множество вспомогательных. потому и написано, что есть основная функция.
2. да. тесты используют тестовые файлы json. а как ещё вы хотите протестировать функцию, которая читает json?

**Comment by tofickbrodaga** [comment]
Спасибо за ответ на топ-1 глупых вопросов
Закрываю ишью
🦡
